### ISSUE TITLE
Reproduce "FedDF" baseline

### ISSUE THREAD

**Issue by hanjialiang** [zhuangdizhu/FedGen#18]
Thank you for open-sourcing your project. I notice that "FedDF" (Ensemble Distillation for Robust Model Fusion in Federated Learning) is one of your baselines in your paper, however, you provide code for only FedAvg, FedProx, FedDistill, and FedGen. Could you please help me reproduce the results of FedDF? I really appreciate your help.

**Comment by ychen404** [comment]
Same here!

**Comment by HLLLLLlll** [comment]
> 感谢您开源您的项目。我注意到“FedDF”（Ensemble Distillation for Robust Model Fusion in Federated Learning）是你论文中的基线之一，但是，你只提供FedAvg、FedProx、FedDistill和FedGen的代码。你能帮我重现FedDF的结果吗？我非常感谢您的帮助。

您好！ 请问您找到FedDF的代码了嘛？

**Comment by zhuangdizhu** [comment]
The FedDF code provided by the paper authors:

https://github.com/epfml/federated-learning-public-code
