### ISSUE TITLE
Network configs: [6, 16, 'F']

### ISSUE THREAD

**Issue by julialohloh** [zhuangdizhu/FedGen#19]
Hi, I'm unable to run any of the files.
This was what is churned out. What does the Network configs: [6, 16, 'F'] mean?
python main.py --dataset Mnist-alpha0.1-ratio0.5 --algorithm FedDistll-FL --batch_size 32 --num_glob_iters 200 --local_epochs 20 --num_users 10 --lamda 1 --learning_rate 0.01 --model cnn --personal_learning_rate 0.01 --times 3
================================================================================
Summary of training process:
Algorithm: FedDistll-FL
Batch size: 32
Learing rate       : 0.01
Ensemble learing rate       : 0.0001
Average Moving       : 1.0
Subset of users      : 10
Number of global rounds       : 200
Number of local rounds       : 20
Dataset       : Mnist-alpha0.1-ratio0.5
Local Model       : cnn
Device            : cpu
================================================================================

         [ Start training iteration 0 ]

Creating model for mnist
Network configs: [6, 16, 'F']
Algorithm FedDistll-FL has not been implemented.

**Comment by szc1999** [comment]
You can change "FedDistll-FL" to “FedDistill-FL”.
the name of algorithm is error.
