### ISSUE TITLE
run the code on cuda device

### ISSUE THREAD

**Issue by daiqing98** [zhuangdizhu/FedGen#6]
It seems that the code does not supprt CUDA? 

--device "cuda" can be set but it seems that it is always running on cpu

Thanks

**Comment by hanjialiang** [comment]
I am curious how you fix this issue. Your reply will be a great help, thank you!

**Comment by daiqing98** [comment]
@hanjialiang It is not implemented. I manually moved the move and tensors to GPU. It is a quick modification and you can try it. When I check the code, it seems the the user_latent_loss (line:58) in userpFedGen.py is the real contribution but not mentioned in the paper if I am right. And the loss functions mentioned in the paper seem unuseful. You may do ablation study to validate it if you are interested.

**Comment by hanjialiang** [comment]
Thank you for your detailed reply. I have tried "os.environ["CUDA_VISIBLE_DEVICES"]", "torch.cuda.set_device()", and model.to(torch.device('cuda:0')), however, the model still runs on CPU. It will be of great help if you tell me how you made that adaption to GPU. Besides, I wonder if it is convenient for you to communicate with me via WeChat or other SNSs for further discussion. Thanks a lot!

**Comment by daiqing98** [comment]
@hanjialiang  Sure. You can email me your contact info.

**Comment by hanjialiang** [comment]
Sorry I did not find your email on your profile. Why not email me via hanjialiang1997@126.com, thank you!
